'use client'

export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as FreePredictions } from './FreePredictions'
export { default as PromoVip } from './PromoVip'
export { default as WinHistory } from './WinHistory'
export { default as Footer } from './Footer'
export { default as CookieConsent } from './CookieConsent'
export { default as AgeVerification } from './AgeVerification'
export { default as FloatingElements } from './FloatingElements'
export { default as CursorEffect } from './CursorEffect'
