import CopyableCode from './CopyableCode'
import Footer from './Footer'
import Navbar from './Navbar'
import CookieConsent from './CookieConsent'
import { AFFILIATE, SITE } from '@/lib/constants'

const sections = [
  { title: 'Le code promo 888starz à retenir', text: 'Le code partenaire présenté sur cette page est btts221, en minuscules. BttsBet le met en avant dans le cadre d’un lien d’affiliation ; l’acceptation du code et toute offre associée doivent être confirmées directement par 888starz.' },
  { title: 'Comment l’utiliser', text: 'Ouvrez le lien partenaire 888starz, créez votre compte si le service est disponible dans votre pays, puis renseignez btts221 dans le champ promotionnel proposé. Si le champ n’est pas affiché, consultez le support ou les conditions de 888starz au lieu de contourner le parcours.' },
  { title: 'Ce qu’il faut vérifier avant un dépôt', text: 'Contrôlez le pays éligible, l’âge légal, le minimum éventuel, les conditions de mise, la durée de l’offre, les limites et les règles de retrait. BttsBet ne garantit aucun bonus, montant, délai ou résultat.' },
]

export default function Star888GuidePage() {
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Article', headline: 'Code promo 888starz btts221', description: 'Guide indépendant du code partenaire 888starz btts221 et des conditions à vérifier.', author: { '@type': 'Organization', name: SITE.name, url: SITE.url }, publisher: { '@type': 'Organization', name: SITE.name, url: SITE.url }, mainEntityOfPage: `${SITE.url}/code-promo-888starz` }
  return <div className="min-h-screen bg-[#050706]"><Navbar /><main className="linebet-shell"><section className="mx-auto max-w-5xl px-5 pb-12 pt-12 sm:px-8 sm:pb-16 sm:pt-20"><p className="linebet-kicker">GUIDE PARTENAIRE · 888STARZ</p><h1 className="mt-4 max-w-4xl text-4xl font-black leading-[1.02] tracking-[-.05em] text-white sm:text-6xl">Code promo 888starz <span className="text-[#ffd4df]">btts221</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#9aaba4] sm:text-lg">Le guide BttsBet pour retrouver le code 888starz, comprendre son utilisation et vérifier les conditions applicables dans votre pays.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center"><a href={AFFILIATE.star888} target="_blank" rel={AFFILIATE.rel} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#f5a3bd] px-5 py-3.5 text-sm font-extrabold text-[#270914] transition hover:bg-[#ffd4df] active:scale-[.98]"><img src="/logos/888starz-icon.svg" alt="" className="h-5 w-5 object-contain" /> Ouvrir 888starz <span aria-hidden="true">↗</span></a><div className="inline-flex items-center justify-center gap-3 rounded-xl border border-[#f5a3bd]/25 bg-[#f5a3bd]/[.06] px-5 py-3.5 text-sm font-bold text-[#ffd4df]">Code : <CopyableCode code="btts221" displayClassName="text-[#ffd4df]" /></div></div></section><section className="border-y border-white/10 bg-[#10090c]"><div className="mx-auto grid max-w-5xl gap-4 px-5 py-10 sm:grid-cols-3 sm:px-8 sm:py-14">{sections.map((section, index) => <article key={section.title} className="linebet-step-card"><span className="linebet-step-number" style={{ color: '#ffd4df' }}>0{index + 1}</span><h2 className="mt-6 text-xl font-extrabold text-white">{section.title}</h2><p className="mt-3 text-sm leading-7 text-[#c3abb2]">{section.text}</p></article>)}</div></section><section className="mx-auto max-w-5xl px-5 py-12 sm:px-8 sm:py-16"><div className="linebet-secondary-card"><p className="linebet-kicker" style={{ color: '#ffd4df' }}>À RETENIR</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em] text-white">888starz · btts221</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[#c3abb2]">Le code doit être saisi en minuscules si le champ est proposé. Vérifiez les conditions officielles 888starz avant toute inscription ou dépôt.</p><a href={AFFILIATE.star888} target="_blank" rel={AFFILIATE.rel} className="mt-6 inline-flex items-center gap-2 rounded-xl border border-[#f5a3bd]/35 bg-[#f5a3bd]/10 px-5 py-3.5 text-sm font-extrabold text-[#ffd4df] transition hover:bg-[#f5a3bd]/15">Vérifier sur 888starz <span aria-hidden="true">↗</span></a></div></section></main><Footer /><CookieConsent /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></div>
}
